name: Read cached files
description: 'Read cached files'
inputs:
  cache_dir:
    description: 'Root path which contains the files that should be cached'
    required: true
  cache_id:
    description: 'The id of the cache'
    required: true
runs:
  using: "composite"
  steps:
    - name: Restore
      uses: actions/cache@v2
      with:
        path: |
          cache_test/cache_test/**/*.txt
          cache_test/cache_test/**/*.md
        key: ${{ inputs.cache_id }}-${{ hashFiles('cache_test/cache_test/**') }}
        restore-keys: |
          ${{ inputs.cache_id }}-${{ hashFiles('cache_test/cache_test/**') }}
          ${{ inputs.cache_id }}-
    - name: Print files (B)
      shell: bash
      run: |
        find cache_test -type f | xargs -t grep -e.
    #- name: Restore
    #  uses: actions/cache@v2
    #  with:
    #    path: |
    #      '${{ inputs.cache_dir }}/**/*.txt'
    #      '${{ inputs.cache_dir }}/**/*.md'
    #    key: ${{ inputs.cache_id }}-${{ hashFiles('${{ inputs.cache_dir }}/**') }}
    #    restore-keys: |
    #      ${{ inputs.cache_id }}-${{ hashFiles('cache_test/**') }}
    #      ${{ inputs.cache_id }}-
