name: Write cached file
description: 'Write cached file'
runs:
  using: "composite"
  steps:
    - name: Create file
      shell: bash
      run: |
        mkdir subdir
        cd subdir
        printf '%s' "Lorem ipsum" >> test_file.txt
    
    - name: Write cache
      uses: actions/cache@v2
      with:
        path: "D:/a/pragma/pragma/**/*.txt"
        key: test-cache-file3
    
