name: build boost
description: 'Attempts to load boost from cache, otherwise rebuilds it.'
runs:
  using: "composite"
  steps:
    - name: Initialize Env
      id: init-env
      uses: Silverlan/common_actions/set_common_env_vars@main
      
    - name: Get boost cache
      id: get-boost-cache
      uses: Silverlan/common_actions/read_build_cache@actions
      with:
        cache_dir: 'third_party_libs/boost'
        cache_id: 'boost-cache-1-76-v4'
        
    - name: Print
      shell: bash
      run: |
        echo "Got a cache hit?: ${{steps.get-boost-cache.outputs.cache-hit}}"
        
    - uses: ChristopherHX/conditional@b4a9649204f81002ec9a4ef7d4bf7d6b2ab7fa55
      name: CMake Build
      with:
        if: "${{steps.get-boost-cache.outputs.cache-hit!='true'}}"
        step: |
          name: Rebuild boost
          uses: Silverlan/pragma/github_actions/rebuild_boost@actions
