name: build boost
description: 'Attempts to load boost from cache, otherwise rebuilds it.'
runs:
  using: "composite"
  steps:
    - name: Initialize Env
      id: init-env
      uses: Silverlan/common_actions/set_common_env_vars@main
      
    - name: Get boost cache
      uses: actions/cache@v2
      id: get-boost-cache
      with:
        path: | 
          "./third_party_libs/boost/boost/*"
          "./third_party_libs/boost/boost/**/*"
          "./third_party_libs/boost/stage/*${{ env.GA_STATIC_LINK_LIBRARY_EXT }}"
          "./third_party_libs/boost/stage/*${{ env.GA_SHARED_BINARY_LIBRARY_EXT }}"
          "./third_party_libs/boost/stage/**/*${{ env.GA_STATIC_LINK_LIBRARY_EXT }}"
          "./third_party_libs/boost/stage/**/*${{ env.GA_SHARED_BINARY_LIBRARY_EXT }}"
        key: boost-cache-1-76-v1
        
    - name: Print
      shell: bash
      run: |
        echo "Got a cache hit?: ${{steps.get-boost-cache.outputs.cache-hit}}"
        
    - uses: ChristopherHX/conditional@b4a9649204f81002ec9a4ef7d4bf7d6b2ab7fa55
      name: CMake Build
      with:
        if: "${{steps.get-boost-cache.outputs.cache-hit=='false'}}"
        step: |
          name: Rebuild boost
          uses: Silverlan/pragma/github_actions/rebuild_boost@actions
